server: 
  port: 8081

spring:
  datasource: 
    url: jdbc:mariadb://localhost/congvandi
    username: root
    password: "*#*#"
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      use-new-id-generator-mappings: true
      # ddl-auto: no
  kafka:
    bootstrapServers: 192.168.1.233:9092
    consumer:
      groupId: congvandi_group

eoffice:
  kafka:
    topic: cong-van-di

logging:
  level:
    org:
      apache:
        kafka:
          clients:
            producer: debug